// examples/ts/react-vite/src/App.jsx
import { useState, useEffect } from 'react'

import { createWaxFoundation } from '@hiveio/wax';

window.waxLoaded = false;

function App() {
  const [version, setVersion] = useState('')

  useEffect(() => {
    createWaxFoundation().then(wax => {
      setVersion(wax.getVersion());

      window.waxLoaded = true;
    });
  }, []);

  return (
    <>
      {version}
    </>
  )
}

export default App

// examples/ts/vue-webpack/src/App.vue
<template>
  <main>You are using wax version: "{{ version }}"</main>
</template>

<script setup>
import { createWaxFoundation } from '@hiveio/wax';
import { ref, onBeforeMount } from 'vue';

const version = ref();

onBeforeMount(async () => {
  const wax = await createWaxFoundation();

  version.value = wax.getVersion();
});
</script>
