// examples/ts/react-vite/src/App.jsx
import { useState, useEffect } from 'react'

import { createWaxFoundation } from '@hiveio/wax/vite';

window.waxLoaded = false;

function App() {
  const [version, setVersion] = useState('')

  useEffect(() => {
    createWaxFoundation().then(wax => {
      setVersion(wax.getVersion());

      window.waxLoaded = true;
    });
  }, []);

  return (
    <>
      {version}
    </>
  )
}

export default App

// examples/ts/nuxt-app/app.vue
<script setup>
import { createWaxFoundation } from "@hiveio/wax/vite";
import { onBeforeMount } from 'vue';

const version = ref('');

onBeforeMount(async () => {
  try {
    const wax = await createWaxFoundation();

    version.value = wax.getVersion();

    window.waxLoaded = true;
  } catch (error) {
    console.error(error);

    window.waxLoaded = false;
  }
});
</script>

<template>
  <div>
    {{ version }}
  </div>
</template>
